### ISSUE TITLE
VnVPlan ready to review

### ISSUE THREAD

**Issue by KarenKarenWang** [KarenKarenWang/cas741_project1#15]
Thanks!!

**Comment by balacij** [comment]
Hi @KarenKarenWang, your VnV plan was a good read. I liked your NFR tests a lot, I think I will need to revise mine. I've completed my review :smile: 

EDIT: I forgot to add: there was a few typos and grammar issues that I think a grammar checker might have been able to catch. If you're not already doing it and you're using VS Code, then you should consider using the [LTeX LanguageTool plugin](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex) for in-LaTeX syntax/grammar/etc. highlighting and suggestions.

**Comment by smiths** [comment]
My comments are in the attached file.
[VnV_Plan_Fdbck.pdf](https://github.com/KarenKarenWang/cas741_project1/files/10872605/VnV_Plan_Fdbck.pdf)
