### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by Maryamvalian** [KarenKarenWang/cas741_project1#16]
- [x] Section 2 You have written "VV" the acronym of verification and Validation. But in other document it is mentioned as "VnV". I think you should keep the consistency.
- [x]  Section 3.1 "The software to test is MATLAB" I think you mean you will test your software written in MATLAB IDE, because you are not going to test the software that you did not develop(MATLAB) but you are going to test your analysis software.
- [x]  Section 3.3 you can add a link to VnV report as a relevant document.
- [x] Section 4.1 It is better to keep it formal and write the full name of VnV team members. Because someone out of this course will not recognize who is Maryam!

**Comment by KarenKarenWang** [comment]
fixed, close for now.
