### ISSUE TITLE
Missing information on VnV

### ISSUE THREAD

**Issue by Maryamvalian** [KarenKarenWang/cas741_project1#17]
- [x] Section 4.1 You have omitted the information on responsibilities. For example, Jason will give feedback on the VnV document as a secondary reviewer or on the MIS document?
- [x]  We all have one primary reviewer and two secondary reviewers more than the professor himself. Also, you have to add another team member.
- [x] Section 4.5 It is better to add details on automated testing. You have written only two words: Python and Matlab! Python is a programming language. You can mention the Pytest library for doing automated tests on your software.

**Comment by KarenKarenWang** [comment]
fixed, close for now.
