### ISSUE TITLE
Test are not clear and complete

### ISSUE THREAD

**Issue by Maryamvalian** [KarenKarenWang/cas741_project1#18]
- [x] Table 1 and Test 1: I think the tests are for checking is the software generating the right answers or not. So you have to complete the output column for table 1 in this document, so that anyone who runs the code, can check if it is correctly working or not.
- [x] Test 2 and Test 3 have the same problem, If there will be out of bound error then the output will be an error message. it is better to show the output message in the tables.
- [x] Are all the inputs integers? because maybe the distance can be 2.5 kilometres? but in your test cases, there are only integers.

**Comment by KarenKarenWang** [comment]
fixed, close for now.
