### ISSUE TITLE
Problem Statement Reviews

### ISSUE THREAD

**Issue by KarenKarenWang** [KarenKarenWang/cas741_project1#2]
Hi, Dr.@smiths, I uploaded the Problem Statement. Could you please have a look?

**Comment by smiths** [comment]
I found your [problem statement](https://github.com/KarenKarenWang/cas741_project1/blob/main/issue/problem_statement.pdf).  It isn't in the problem statement folder, but in a new folder you created called issue.  I'll review the problem statement below, but please move the files back to the problem statement folder and delete the issue folder. 

The problem statement doesn't really capture the inputs and outputs.  I'm thinking something like the following:

Your input is an abstract model of a grid of data centres and a power distribution grid.  You need the distance between each data centre and each power source.  For each data centre you have the load on the grid.  For each power source you can have the cost and the CO2 load.  Your output would be the cost, energy lost over the transmission lines and CO2.  This would let us compare different configurations where we have more renewable energy and where we move the computation (load) to data centres with extra energy.

I could image a control algorithm for the above, where the load and power change over time.  I think a static analysis would probably be enough to start.

Some references would really help your problem statement.

You probably will use Matlab and Simulink, but you shouldn't mention that in your problem statement (or SRS).  We want to stay abstract at this stage.  That is, we don't want to prematurely make design decisions.

Although there is work to do on understanding your problem, I'm going to approve your problem statement.  We can do the work as we prepare your SRS.  However, you should review my comments above when preparing your SRS.
