### ISSUE TITLE
Empty “List of Figures” Section can be removed

### ISSUE THREAD

**Issue by balacij** [KarenKarenWang/cas741_project1#25]

**Comment by smiths** [comment]
The linked commit (550ef04b54b7771d2403991ebf72df9e8011aa39) only has one change (the addition of a space).  It does not address this issue (or the other 5 issues it is said to close).

**Comment by KarenKarenWang** [comment]
Hi Dr.Smith,
 I made that by mistake, I made all the changes on the file when for 19-22
issues. So should I reopen these issues and push again? Or is there any way
I can fix this;_;

Thanks,
Karen

Spencer Smith ***@***.***>于2023年5月4日 周四上午6:57写道：

**Comment by smiths** [comment]
Hello @KarenKarenWang.  No, you don't have to reopen the issues.  In the future, please do incremental commits.  For each issues you do the following: fix the problem, commit the changes, close the issue with a link to the commit that fixes the problem.

**Comment by KarenKarenWang** [comment]
Hi Dr.Smith,

I will do that for future and the rest of issues.

Thanks,
Ning

Spencer Smith ***@***.***>于2023年5月4日 周四上午11:44写道：
