### ISSUE TITLE
MG+MIS uploladed

### ISSUE THREAD

**Issue by KarenKarenWang** [KarenKarenWang/cas741_project1#34]
Dear Dr.@smiths ,
My [docs](https://github.com/KarenKarenWang/cas741_project1/tree/main/docs/MG%2BMIS) are ready for review.

Thanks，
Karen

**Comment by smiths** [comment]
Feedback is in the attached files.
[MG_Fdbck.pdf](https://github.com/KarenKarenWang/cas741_project1/files/11206948/MG_Fdbck.pdf)
[MIS_Fdbck.pdf](https://github.com/KarenKarenWang/cas741_project1/files/11206951/MIS_Fdbck.pdf)
