### ISSUE TITLE
MG Review-part1

### ISSUE THREAD

**Issue by MinMah23** [KarenKarenWang/cas741_project1#36]
Here are some suggestions, I hope it'll be helpful.
- [x] Revision History and Reference Material which includes abbreviation and acronyms are missed.
- [x] List of tables is missed.
- [x] List of Figures is missed.
- [x] References in Introduction section are missed.
- [x] It's a kind suggestion you can rewrite AC1 as "The number of Data Centers".
- [x] I might be wrong but as I remember, the AC2 to AC6 are your program inputs
- [x] I think AC 7,8 , 10 is code-level decision but this document is design-level decisions.
- [x] Most of the ACs are detailed and implementation-level, you can make them more abstract.
- [x] In UC1, I think you meant input format instead of "devices".
- [x] In UC2, "Remove the check for valid distance values between 0 and 2000", you means you always check the validity of input?
- [x] I think it's better to review the format of UCs (4,5,6,7, and 8). what is meant by UC8?
- [x] You have a module for checking the inputs validation, M3, doesn't it cover AC9?
- [x] In " It will not be reimplemented. and M7 are already available in Matlab and will not be reimplemented.", the ". and"  should be corrected.
- [x] I think M9 and M10 also implemented by Matlab, if it's OK, add them to M&, at the end of the paragraph.
- [x] References should be added in "Modules are decomposed according to the principle of “information hiding” proposed by ?." instead of "?".

**Comment by smiths** [comment]
Many of the above changes weren't actually made, like adding the list of tables, figures, references, etc.

**Comment by KarenKarenWang** [comment]
Hi Dr.Smith,

I did not make those changes since some of my docs like MIS and MG do not
have a reference, and like MIS and VnV plan does not have figures. Shall I
add these sections and add a comment said not applicable at this point?

Karen

Spencer Smith ***@***.***> 于2023年5月5日周五 11:12写道：

**Comment by smiths** [comment]
The typical approach is to include sections from the template even when they aren't relevant, and then enter not applicable.  Alternatively, the reason for not addressing the feedback can be provided.  The comment about the figures was just one example.  Most of the above feedback was not implemented in the revised version.  Although not part of this issue, much of the feedback I provided was also not addressed.

I'm afraid that there isn't time for another iteration.  I need to grade was is submitted so that I can get the grades in by the deadline.

**Comment by KarenKarenWang** [comment]
Thank you for the clarification. I had uploaded the reverse SRS, it was
missing before. Sorry for the delay. I will improve these mistakes for my
future masterworks, please take your time to grade me and submitted. Thank
you so much for taking time helping me.

karen

Spencer Smith ***@***.***> 于2023年5月5日周五 11:34写道：
