### ISSUE TITLE
SRS reverse uploaded

### ISSUE THREAD

**Issue by KarenKarenWang** [KarenKarenWang/cas741_project1#45]
Hi Dr @smiths 
I have uploaded a reverse [SRS.](https://github.com/KarenKarenWang/cas741_project1/tree/main/docs/SRS) Sorry for the delay.

Karen

**Comment by smiths** [comment]
Okay, I will grade the revisions of the SRS.

**Comment by KarenKarenWang** [comment]
Thanks, sir

karen


Spencer Smith ***@***.***> 于2023年5月5日周五 11:53写道：
